language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

branches:
  only:
    - io-refactor
    - master
    - refactor/performance-refactor

addons:
  apt:
    packages:
      - gdal-bin
      - libproj-dev
      - libhdf5-serial-dev
      - libpng12-dev
      - libgdal-dev
      - libatlas-dev
      - libatlas-base-dev
      - gfortran
      - oracle-java8-set-default

before_install:
  - cd geopyspark-backend && ./sbt "project geotrellis-backend" assembly
  - cp geotrellis/target/scala-2.11/geotrellis-backend-assembly-0.1.0.jar ../geopyspark/jars
  - cd ..

install:
  - pip3 install -r requirements.txt
  - pip3 install pyproj
  - pip3 install .

cache:
  directories:
  - ./archives
  - $HOME/.ivy2
  - $HOME/.cache/pip

script:
  - "if [ ! -f archives/spark-2.1.0-bin-hadoop2.7.tgz ]; then pushd archives ; wget http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz; popd; fi"
  - "tar -xvf archives/spark-2.1.0-bin-hadoop2.7.tgz"
  - "export SPARK_HOME=./spark-2.1.0-bin-hadoop2.7/"
  - "export JAVA_HOME=/usr/lib/jvm/java-8-oracle"
  - pytest -k "schema" geopyspark/tests/schema_tests/
  - pytest -k "not schema" geopyspark/tests/*test.py
